name: MultiRespawn
version: ${version}
main: net.astroalchemist.multirespawn.MultiRespawn
api-version: "1.21"
folia-supported: true
author: AstroAlchemist
description: Cross-server respawn with /back command
website: https://github.com/altugcetin/MultiRespawn

commands:
  multirespawn:
    description: Main command for MultiRespawn plugin
    aliases: [mr]
    usage: /<command> [reload|info]
    permission: multirespawn.admin
  back:
    description: Teleport to death location
    usage: /<command>
    permission: multirespawn.back

permissions:
  multirespawn.admin:
    description: Access to admin commands
    default: op
  multirespawn.bypass:
    description: Bypass cross-server respawn
    default: false
  multirespawn.back:
    description: Use /back command
    default: true
